# Generated by Django 3.0.3 on 2020-08-26 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_answervotes_entry_questions_questionvotes_userdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='Views',
            field=models.IntegerField(default=0),
        ),
    ]
